apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: d21-sample-spring-boot-app-k8s
build:
  artifacts:
    - image: d1-cnoe/d21-sample-spring-boot-app-k8s
      jib:
        args:
          - -Pjib
          - -DskipTests
manifests:
  rawYaml:
    - k8s/deployment.yaml
deploy:
  kubectl: {}